/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-22 06:01:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.includes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1744610463796L));
    _jspx_dependants.put("jar:file:/C:/Users/user/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("  html {\n");
      out.write("    height: 100%;\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  body {\n");
      out.write("    min-height: 100%;\n");
      out.write("    display: flex;\n");
      out.write("    flex-direction: column;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .content-wrapper {\n");
      out.write("    flex: 1 0 auto;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  footer {\n");
      out.write("    background: linear-gradient(to bottom, #031f3a, #123359);\n");
      out.write("    color: #ffffff;\n");
      out.write("    flex-shrink: 0;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  footer h5 {\n");
      out.write("    color: #ffffff;\n");
      out.write("    font-weight: bold;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  footer a {\n");
      out.write("    color: #ffffff !important;\n");
      out.write("    transition: color 0.3s ease;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  footer a:hover {\n");
      out.write("    color: #ffffff !important;\n");
      out.write("    text-decoration: none;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  footer .border-top {\n");
      out.write("    border-top-color: #ffffff !important;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  footer i {\n");
      out.write("    color: #ffffff;\n");
      out.write("  }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<footer class=\"py-4 mt-auto\">\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("      <div class=\"col-md-4 mb-4\">\n");
      out.write("        <h5 class=\"mb-3\">Movie Rental</h5>\n");
      out.write("        <p class=\"text-light\" style=\"font-size: 0.9rem;\">\n");
      out.write("          Your one-stop destination for renting the latest and greatest movies. Enjoy from the comfort of your home.\n");
      out.write("        </p>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"col-md-4 mb-4\">\n");
      out.write("        <h5 class=\"mb-3\">Quick Links</h5>\n");
      out.write("        <ul class=\"list-unstyled\">\n");
      out.write("          <li class=\"mb-2\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"text-decoration-none\">Movies</a>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"col-md-4 mb-4\">\n");
      out.write("        <h5 class=\"mb-3\">Contact Us</h5>\n");
      out.write("        <ul class=\"list-unstyled\">\n");
      out.write("          <li class=\"mb-2\">\n");
      out.write("            <i class=\"bi bi-geo-alt-fill me-2\"></i>\n");
      out.write("            SLIIT Malabe Campus, New Kandy Rd, Malabe.\n");
      out.write("          </li>\n");
      out.write("          <li class=\"mb-2\">\n");
      out.write("            <i class=\"bi bi-telephone-fill me-2\"></i>\n");
      out.write("            (012) 345-6789\n");
      out.write("          </li>\n");
      out.write("          <li class=\"mb-2\">\n");
      out.write("            <i class=\"bi bi-envelope-fill me-2\"></i>\n");
      out.write("            info@movierentalapp.com\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"text-center pt-3 mt-3 border-top\">\n");
      out.write("    <p class=\"mb-0\" style=\"font-size: 0.9rem;\">&copy; 2023 Movie Rental. All rights reserved.</p>\n");
      out.write("  </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
