/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-20 10:07:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1744610463796L));
    _jspx_dependants.put("jar:file:/C:/Users/user/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Admin Dashboard - Movie Rental</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        html, body {\n");
      out.write("            height: 100%;\n");
      out.write("            margin: 0;\n");
      out.write("            background-color: #f8f9fa;\n");
      out.write("        }\n");
      out.write("        body {\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            min-height: 100vh;\n");
      out.write("        }\n");
      out.write("        .content-wrapper {\n");
      out.write("            flex: 1 0 auto;\n");
      out.write("            width: 100%;\n");
      out.write("            padding-bottom: 20px;\n");
      out.write("            background-color: #f8f9fa;\n");
      out.write("        }\n");
      out.write("        footer {\n");
      out.write("            flex-shrink: 0;\n");
      out.write("            width: 100%;\n");
      out.write("        }\n");
      out.write("        footer .list-unstyled li {\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("        }\n");
      out.write("        footer .text-decoration-none {\n");
      out.write("            color: #ffffff !important;\n");
      out.write("        }\n");
      out.write("        footer .bi {\n");
      out.write("            margin-right: 0.5rem;\n");
      out.write("        }\n");
      out.write("        .navbar {\n");
      out.write("            background: linear-gradient(to bottom, #031f3a, #123359) !important;\n");
      out.write("            padding: 1rem 0;\n");
      out.write("        }\n");
      out.write("        .navbar-brand {\n");
      out.write("            color: #ffffff !important;\n");
      out.write("            font-weight: bold;\n");
      out.write("            font-size: 1.5rem;\n");
      out.write("            transition: color 0.3s ease;\n");
      out.write("        }\n");
      out.write("        .navbar-brand:hover {\n");
      out.write("            color: #ffffff !important;\n");
      out.write("            opacity: 0.9;\n");
      out.write("        }\n");
      out.write("        .nav-link {\n");
      out.write("            color: #ffffff !important;\n");
      out.write("            transition: color 0.3s ease;\n");
      out.write("            font-weight: 500;\n");
      out.write("            padding: 0.5rem 1rem;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        .nav-link:hover {\n");
      out.write("            color: #ffffff !important;\n");
      out.write("            opacity: 0.9;\n");
      out.write("            background-color: rgba(255, 255, 255, 0.1);\n");
      out.write("        }\n");
      out.write("        .nav-link::after {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            width: 0;\n");
      out.write("            height: 2px;\n");
      out.write("            bottom: 0;\n");
      out.write("            left: 50%;\n");
      out.write("            background: #ffffff;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            transform: translateX(-50%);\n");
      out.write("        }\n");
      out.write("        .nav-link:hover::after {\n");
      out.write("            width: 80%;\n");
      out.write("        }\n");
      out.write("        .nav-link.active {\n");
      out.write("            background-color: rgba(255, 255, 255, 0.2);\n");
      out.write("        }\n");
      out.write("        .nav-link.active::after {\n");
      out.write("            width: 80%;\n");
      out.write("        }\n");
      out.write("        .navbar-toggler {\n");
      out.write("            border-color: rgba(255, 255, 255, 0.5);\n");
      out.write("        }\n");
      out.write("        .navbar-toggler-icon {\n");
      out.write("            background-image: url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'%3e%3cpath stroke='rgba%28255, 255, 255, 0.75%29' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e\");\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /* Dashboard specific styles */\n");
      out.write("        .card {\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .card:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .card-header {\n");
      out.write("            background: linear-gradient(135deg, #031f3a, #123359);\n");
      out.write("            color: white;\n");
      out.write("            border-radius: 10px 10px 0 0 !important;\n");
      out.write("            padding: 1rem 1.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .card-header h5 {\n");
      out.write("            margin: 0;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .card-body {\n");
      out.write("            padding: 1.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .welcome-card {\n");
      out.write("            background: linear-gradient(135deg, #031f3a, #123359);\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .welcome-card .card-body {\n");
      out.write("            padding: 2rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .welcome-card h2 {\n");
      out.write("            font-size: 1.8rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .welcome-card p {\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("            opacity: 0.9;\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .stats-card {\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .stats-card:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .stats-card .card-body {\n");
      out.write("            padding: 1.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .stats-card .card-title {\n");
      out.write("            font-size: 1rem;\n");
      out.write("            font-weight: 500;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("            opacity: 0.9;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .stats-card .card-text {\n");
      out.write("            font-size: 2rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .bg-primary {\n");
      out.write("            background: linear-gradient(135deg, #031f3a, #123359) !important;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .bg-success {\n");
      out.write("            background: linear-gradient(135deg, #1a472a, #2d5a3f) !important;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .bg-info {\n");
      out.write("            background: linear-gradient(135deg, #0c4b6e, #1a6b94) !important;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .bg-warning {\n");
      out.write("            background: linear-gradient(135deg, #856404, #b38a00) !important;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <nav class=\"navbar navbar-expand-lg\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/dashboard\">Movie Rental</a>\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\">\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("            </button>\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n");
      out.write("                <ul class=\"navbar-nav me-auto\">\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link active\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/dashboard\">Dashboard</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/admins\">Admins</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("                <ul class=\"navbar-nav\">\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/profile\">Profile</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\">Logout</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"content-wrapper\">\n");
      out.write("        <div class=\"container mt-4\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <!-- Welcome Card -->\n");
      out.write("                <div class=\"col-md-12 mb-4\">\n");
      out.write("                    <div class=\"card welcome-card\">\n");
      out.write("                        <div class=\"card-body\">\n");
      out.write("                            <h2>Welcome, ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.fullName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("!</h2>\n");
      out.write("                            <p>This is your admin dashboard where you can manage the Movie rental system.</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/@popperjs/core@2.11.6/dist/umd/popper.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    <script>\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("            var dropdowns = document.querySelectorAll('.dropdown-toggle');\n");
      out.write("            dropdowns.forEach(function(dropdown) {\n");
      out.write("                new bootstrap.Dropdown(dropdown);\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("\n");
      out.write("\n");
      out.write("        function loadDashboardData() {\n");
      out.write("\n");
      out.write("            fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/api/admin/stats/users')\n");
      out.write("                .then(response => response.json())\n");
      out.write("                .then(data => {\n");
      out.write("                    document.getElementById('totalUsers').textContent = data.total;\n");
      out.write("                });\n");
      out.write("\n");
      out.write("            fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/api/admin/stats/products')\n");
      out.write("                .then(response => response.json())\n");
      out.write("                .then(data => {\n");
      out.write("                    document.getElementById('totalProducts').textContent = data.total;\n");
      out.write("                });\n");
      out.write("\n");
      out.write("            fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/api/admin/stats/rentals/active')\n");
      out.write("                .then(response => response.json())\n");
      out.write("                .then(data => {\n");
      out.write("                    document.getElementById('activeRentals').textContent = data.total;\n");
      out.write("                });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("\n");
      out.write("        document.addEventListener('DOMContentLoaded', loadDashboardData);\n");
      out.write("\n");
      out.write("        setInterval(loadDashboardData, 300000);\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
