/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-20 10:08:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1744610463796L));
    _jspx_dependants.put("jar:file:/C:/Users/user/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Admin Profile - Movie Rental</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        html, body {\n");
      out.write("            height: 100%;\n");
      out.write("            margin: 0;\n");
      out.write("            background-color: #f8f9fa;\n");
      out.write("        }\n");
      out.write("        body {\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            min-height: 100vh;\n");
      out.write("        }\n");
      out.write("        .content-wrapper {\n");
      out.write("            flex: 1 0 auto;\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 3rem 0 20px;\n");
      out.write("            background-color: #f8f9fa;\n");
      out.write("        }\n");
      out.write("        .navbar {\n");
      out.write("            background: linear-gradient(to bottom, #031f3a, #123359) !important;\n");
      out.write("            padding: 1rem 0;\n");
      out.write("        }\n");
      out.write("        .navbar-brand {\n");
      out.write("            color: #ffffff !important;\n");
      out.write("            font-weight: bold;\n");
      out.write("            font-size: 1.5rem;\n");
      out.write("            transition: color 0.3s ease;\n");
      out.write("        }\n");
      out.write("        .navbar-brand:hover {\n");
      out.write("            color: #ffffff !important;\n");
      out.write("            opacity: 0.9;\n");
      out.write("        }\n");
      out.write("        .nav-link {\n");
      out.write("            color: #ffffff !important;\n");
      out.write("            transition: color 0.3s ease;\n");
      out.write("            font-weight: 500;\n");
      out.write("            padding: 0.5rem 1rem;\n");
      out.write("            border-radius: 4px;\n");
      out.write("        }\n");
      out.write("        .nav-link:hover {\n");
      out.write("            color: #ffffff !important;\n");
      out.write("            opacity: 0.9;\n");
      out.write("            background-color: rgba(255, 255, 255, 0.1);\n");
      out.write("        }\n");
      out.write("        .nav-link.active {\n");
      out.write("            background-color: rgba(255, 255, 255, 0.2);\n");
      out.write("        }\n");
      out.write("        .navbar-toggler {\n");
      out.write("            border-color: rgba(255, 255, 255, 0.5);\n");
      out.write("        }\n");
      out.write("        .navbar-toggler-icon {\n");
      out.write("            background-image: url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'%3e%3cpath stroke='rgba%28255, 255, 255, 0.75%29' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e\");\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .profile-card {\n");
      out.write("            background: white;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .profile-card:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-header {\n");
      out.write("            background: linear-gradient(to bottom, #031f3a, #123359);\n");
      out.write("            color: white;\n");
      out.write("            border-radius: 10px 10px 0 0 !important;\n");
      out.write("            padding: 1.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-header h5 {\n");
      out.write("            margin: 0;\n");
      out.write("            font-weight: 600;\n");
      out.write("            font-size: 1.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-body {\n");
      out.write("            padding: 2rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-label {\n");
      out.write("            font-weight: 500;\n");
      out.write("            color: #031f3a;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control {\n");
      out.write("            border-radius: 8px;\n");
      out.write("            border: 1px solid #dee2e6;\n");
      out.write("            padding: 0.75rem 1rem;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control:focus {\n");
      out.write("            border-color: #123359;\n");
      out.write("            box-shadow: 0 0 0 0.2rem rgba(18, 51, 89, 0.25);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control:read-only {\n");
      out.write("            background-color: #f8f9fa;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary {\n");
      out.write("            background: linear-gradient(to bottom, #031f3a, #123359);\n");
      out.write("            border: none;\n");
      out.write("            padding: 0.75rem 1.5rem;\n");
      out.write("            font-weight: 500;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary:hover {\n");
      out.write("            background: linear-gradient(to bottom, #123359, #031f3a);\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 4px 8px rgba(0,0,0,0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .section-divider {\n");
      out.write("            border-top: 2px solid #eee;\n");
      out.write("            margin: 2rem 0;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .section-divider h6 {\n");
      out.write("            position: absolute;\n");
      out.write("            top: -12px;\n");
      out.write("            left: 0;\n");
      out.write("            background: white;\n");
      out.write("            padding: 0 1rem;\n");
      out.write("            color: #031f3a;\n");
      out.write("            font-weight: 600;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .alert {\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 1rem 1.5rem;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            border: none;\n");
      out.write("            box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .alert-success {\n");
      out.write("            background: linear-gradient(135deg, #1a472a, #2d5a3f);\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .alert-danger {\n");
      out.write("            background: linear-gradient(135deg, #dc3545, #c82333);\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <nav class=\"navbar navbar-expand-lg\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/dashboard\">Movie Rental</a>\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\">\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("            </button>\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n");
      out.write("                <ul class=\"navbar-nav me-auto\">\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/dashboard\">Dashboard</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/admins\">Admins</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("                <ul class=\"navbar-nav\">\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link active\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/profile\">Profile</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\">Logout</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <div class=\"content-wrapper\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("        <div class=\"row justify-content-center\">\n");
      out.write("            <div class=\"col-md-8\">\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"profile-card\">\n");
      out.write("                    <div class=\"card-header\">\n");
      out.write("                            <h5><i class=\"fas fa-user-circle me-2\"></i>Admin Profile</h5>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <form id=\"profileForm\" onsubmit=\"updateProfile(event)\">\n");
      out.write("                                <div class=\"mb-4\">\n");
      out.write("                                <label for=\"username\" class=\"form-label\">Username</label>\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"username\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                                <div class=\"mb-4\">\n");
      out.write("                                <label for=\"fullName\" class=\"form-label\">Full Name</label>\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"fullName\" name=\"fullName\" \n");
      out.write("                                       value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.fullName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                                <div class=\"mb-4\">\n");
      out.write("                                <label for=\"email\" class=\"form-label\">Email</label>\n");
      out.write("                                <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" \n");
      out.write("                                       value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                                <div class=\"section-divider\">\n");
      out.write("                            <h6>Change Password</h6>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"mb-4\">\n");
      out.write("                                <label for=\"currentPassword\" class=\"form-label\">Current Password</label>\n");
      out.write("                                <input type=\"password\" class=\"form-control\" id=\"currentPassword\" name=\"currentPassword\">\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                                <div class=\"mb-4\">\n");
      out.write("                                <label for=\"newPassword\" class=\"form-label\">New Password</label>\n");
      out.write("                                <input type=\"password\" class=\"form-control\" id=\"newPassword\" name=\"newPassword\" \n");
      out.write("                                       minlength=\"6\">\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                                <div class=\"mb-4\">\n");
      out.write("                                <label for=\"confirmPassword\" class=\"form-label\">Confirm New Password</label>\n");
      out.write("                                    <input type=\"password\" class=\"form-control\" id=\"confirmPassword\" name=\"confirmPassword\" \n");
      out.write("                                       minlength=\"6\">\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                                <div class=\"d-flex justify-content-between align-items-center\">\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-primary\">\n");
      out.write("                                        <i class=\"fas fa-save me-2\"></i>Save Changes\n");
      out.write("                                    </button>\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-danger\" data-bs-toggle=\"modal\" data-bs-target=\"#deleteAccountModal\">\n");
      out.write("                                        <i class=\"fas fa-trash-alt me-2\"></i>Delete Account\n");
      out.write("                                    </button>\n");
      out.write("                            </div>\n");
      out.write("                        </form>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"modal fade\" id=\"deleteAccountModal\" tabindex=\"-1\" aria-labelledby=\"deleteAccountModalLabel\" aria-hidden=\"true\">\n");
      out.write("        <div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                <div class=\"modal-header\">\n");
      out.write("                    <h5 class=\"modal-title\" id=\"deleteAccountModalLabel\">Delete Account</h5>\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-body\">\n");
      out.write("                    <p class=\"text-danger\">Warning: This action cannot be undone. All your data will be permanently deleted.</p>\n");
      out.write("                    <form id=\"deleteAccountForm\" onsubmit=\"deleteAccount(event)\">\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label for=\"password\" class=\"form-label\">Enter your password to confirm</label>\n");
      out.write("                            <input type=\"password\" class=\"form-control\" id=\"password\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"d-grid\">\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-danger\">Delete Account</button>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    <script>\n");
      out.write("        function updateProfile(event) {\n");
      out.write("            event.preventDefault();\n");
      out.write("\n");
      out.write("            const currentPassword = document.getElementById('currentPassword').value;\n");
      out.write("            const newPassword = document.getElementById('newPassword').value;\n");
      out.write("            const confirmPassword = document.getElementById('confirmPassword').value;\n");
      out.write("\n");
      out.write("            if ((currentPassword || newPassword || confirmPassword) &&\n");
      out.write("                (currentPassword === '' || newPassword === '' || confirmPassword === '')) {\n");
      out.write("                alert('Please fill in all password fields to change your password');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            if (newPassword !== confirmPassword) {\n");
      out.write("                alert('New passwords do not match');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            const data = {\n");
      out.write("                fullName: document.getElementById('fullName').value,\n");
      out.write("                email: document.getElementById('email').value\n");
      out.write("            };\n");
      out.write("\n");
      out.write("            if (currentPassword && newPassword) {\n");
      out.write("                data.currentPassword = currentPassword;\n");
      out.write("                data.newPassword = newPassword;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/profile', {\n");
      out.write("                method: 'POST',\n");
      out.write("                headers: {\n");
      out.write("                    'Content-Type': 'application/json',\n");
      out.write("                },\n");
      out.write("                body: JSON.stringify(data)\n");
      out.write("            })\n");
      out.write("            .then(response => {\n");
      out.write("                if (!response.ok) {\n");
      out.write("                    return response.text().then(text => {\n");
      out.write("                        throw new Error(text || 'Failed to update profile');\n");
      out.write("                    });\n");
      out.write("                }\n");
      out.write("                return response.json();\n");
      out.write("            })\n");
      out.write("            .then(data => {\n");
      out.write("                if (data.success) {\n");
      out.write("                    window.location.reload();\n");
      out.write("                } else {\n");
      out.write("                    throw new Error(data.message || 'Failed to update profile');\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("            .catch(error => {\n");
      out.write("                alert(error.message);\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function deleteAccount(event) {\n");
      out.write("            event.preventDefault();\n");
      out.write("            const password = document.getElementById('password').value;\n");
      out.write("\n");
      out.write("            fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/delete-account', {\n");
      out.write("                method: 'POST',\n");
      out.write("                headers: {\n");
      out.write("                    'Content-Type': 'application/json',\n");
      out.write("                },\n");
      out.write("                body: JSON.stringify({ password: password })\n");
      out.write("            })\n");
      out.write("            .then(response => {\n");
      out.write("                if (!response.ok) {\n");
      out.write("                    return response.text().then(text => {\n");
      out.write("                        throw new Error(text || 'Failed to delete account');\n");
      out.write("                    });\n");
      out.write("                }\n");
      out.write("                return response.json();\n");
      out.write("            })\n");
      out.write("            .then(data => {\n");
      out.write("                if (data.success) {\n");
      out.write("                    window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/';\n");
      out.write("                } else {\n");
      out.write("                    throw new Error(data.message || 'Failed to delete account');\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("            .catch(error => {\n");
      out.write("                alert(error.message);\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/admin/profile.jsp(197,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty success}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("                        <div class=\"alert alert-success alert-dismissible fade show\" role=\"alert\">\n");
        out.write("                            ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${success}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\n");
        out.write("                            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\n");
        out.write("                        </div>\n");
        out.write("                    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/views/admin/profile.jsp(203,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty error}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("                        <div class=\"alert alert-danger alert-dismissible fade show\" role=\"alert\">\n");
        out.write("                            ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\n");
        out.write("                            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\n");
        out.write("                        </div>\n");
        out.write("                    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
